<div class="col-sm-10 offset-sm-1">

    <div class="row">
        <div class="col-sm-6">
            <h4>Países:</h4>
        </div>
        <?php if ($this->activeUser != new \app\model\UserModel() && $this->activeUser->getTypeUser() != "U") { ?>
            <div class="col-sm-6 text-right">
                <a href="/Metalpedia/paises/cadastrar">
                    <button type="button" class="btn btn-danger btn-sm">
                        <i class="fas fa-plus"></i> Cadastrar
                    </button>
                </a>
            </div>
        <?php } ?>
    </div>

    <!--<form name="searchform" method="post" action="Request.php?class=CountryCtr&method=showList&page=1">-->
    <form name="searchform" method="post" action="/Metalpedia/paises?page=1">

        <table class="table table-dark table-borderless">
            <thead>
            <tr>
                <th>Reg. Por Página:</th>
                <th>Nome, ISO ou ISO3:</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    <select class="custom-select" name="limit" id="limit">
                        <option <?= $this->regPerPage == 10 ? "selected" : '' ?> value="10">10</option>
                        <option <?= $this->regPerPage == 25 ? "selected" : '' ?> value="25">25</option>
                        <option <?= $this->regPerPage == 50 ? "selected" : '' ?> value="50">50</option>
                        <option <?= $this->regPerPage == 100 ? "selected" : '' ?> value="100">100</option>
                    </select>
                </td>
                <td>
                    <div class="input-group">
                        <input type="text" class="form-control custom-input" name="data[0]" id="name" value="<?= $this->sqlData[0] ?>" placeholder="Pesquisar...">
                        <div class="input-group-append">
                            <button class="btn btn-danger" type="submit" name="command" title="Pesquisar"><i class="fas fa-filter fa-sm"></i> Filtrar</button>
                        </div>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>

    </form>

    <div id="view-list" class="card-group mt-5">
        <?php if (sizeof($this->model) == 0) { ?>
            <div class="container-fluid mt-3 text-center">
                <span>Nenhum Registro Encontrado!</span>
            </div>
        <?php } ?>

        <?php foreach ($this->model as $country) { ?>

            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6 mb-4">

                <form name="<?=$country->getId()?>" action="/Metalpedia/bandas?page=1" method="post">

                    <input type="hidden" name="data[0]" value="<?=$country->getId()?>">

                    <div class="grid__item">
                        <!--<a class="grid__link" href="/Metalpedia/paises/editar/<?/*=$country->getId()*/?>" title="<?/*=$country->getNameCountry()*/?>">-->
                        <a onclick="f('<?=$country->getId()?>')" class="grid__link" href="/Metalpedia/bandas" title="<?=$country->getNameCountry()?>">
                            <div class="img-wrap img-wrap--grid">
                                <img class="img img--grid" src="core/img/flags/<?=$country->getFlagCountry()?>" alt="album1">
                            </div>
                        </a>
                        <?php if ($this->activeUser != new \app\model\UserModel() && $this->activeUser->getTypeUser() == 'A') { ?>
                            <span class="type border-0">
                                <a href="/Metalpedia/paises/editar/<?=$country->getId()?>">
                                    <button type="button" class="btn btn-danger btn-sm">
                                        <i class="fas fa-cog"></i>
                                    </button>
                                </a>
                            </span>
                        <?php } ?>
                        <span class="year"><?=$country->getIsoCountry()?> | <?=$country->getIso3Country()?></span>
                        <span class="artist"></span>
                        <span class="title"><?=$country->getNameCountry()?></span>
                    </div>

                </form>

            </div>

        <?php } ?>
    </div>

    <?php
        $this->createPagination('CountryCtr');
    ?>

    <?php
    /*$this->createList(
        $this->model,
        array('Nome', 'ISO', 'ISO3', 'Bandeira'),
        array('getNameCountry', 'getIsoCountry', 'getIso3Country', 'getFlagCountry'),
        'CountryCtr'
    );*/

    ?>

</div>

<script !src="">
    function f(i) {
        var form = document.getElementsByName(i)[0];
        this.addEventListener('click', function (e) {
            e.preventDefault();
            form.submit();
        });
    }
</script>