INSERT INTO genre (id_genre, name_genre) VALUES (DEFAULT, 'Alternative Metal');
INSERT INTO genre (id_genre, name_genre) VALUES (DEFAULT, 'Black Metal');
INSERT INTO genre (id_genre, name_genre) VALUES (DEFAULT, 'Death Metal');
INSERT INTO genre (id_genre, name_genre) VALUES (DEFAULT, 'Deathcore');
INSERT INTO genre (id_genre, name_genre) VALUES (DEFAULT, 'Doom Metal');
INSERT INTO genre (id_genre, name_genre) VALUES (DEFAULT, 'Folk Metal');
INSERT INTO genre (id_genre, name_genre) VALUES (DEFAULT, 'Ghotic Metal');
INSERT INTO genre (id_genre, name_genre) VALUES (DEFAULT, 'Glam Metal');
INSERT INTO genre (id_genre, name_genre) VALUES (DEFAULT, 'Hard Rock');
INSERT INTO genre (id_genre, name_genre) VALUES (DEFAULT, 'Hardcore');
INSERT INTO genre (id_genre, name_genre) VALUES (DEFAULT, 'Heavy Metal');
INSERT INTO genre (id_genre, name_genre) VALUES (DEFAULT, 'Industrial Metal');
INSERT INTO genre (id_genre, name_genre) VALUES (DEFAULT, 'Metalcore');
INSERT INTO genre (id_genre, name_genre) VALUES (DEFAULT, 'Nu Metal');
INSERT INTO genre (id_genre, name_genre) VALUES (DEFAULT, 'Post-Metal');
INSERT INTO genre (id_genre, name_genre) VALUES (DEFAULT, 'Power Metal');
INSERT INTO genre (id_genre, name_genre) VALUES (DEFAULT, 'Progressive Metal');
INSERT INTO genre (id_genre, name_genre) VALUES (DEFAULT, 'Sludge Metal');
INSERT INTO genre (id_genre, name_genre) VALUES (DEFAULT, 'Speed Metal');
INSERT INTO genre (id_genre, name_genre) VALUES (DEFAULT, 'Stoner Metal');
INSERT INTO genre (id_genre, name_genre) VALUES (DEFAULT, 'Symphonic Metal');
INSERT INTO genre (id_genre, name_genre) VALUES (DEFAULT, 'Thrash Metal');