INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (1, 'Andorra', 'AD', 'AND', 'ad.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (2, 'United Arab Emirates', 'AE', 'ARE', 'ae.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (3, 'Afghanistan', 'AF', 'AFG', 'af.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (4, 'Antigua and Barbuda', 'AG', 'ATG', 'ag.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (5, 'Anguilla', 'AI', 'AIA', 'ai.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (6, 'Albania', 'AL', 'ALB', 'al.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (7, 'Armenia', 'AM', 'ARM', 'am.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (8, 'Angola', 'AO', 'AGO', 'ao.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (9, 'Antarctica', 'AQ', 'ATA', 'aq.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (10, 'Argentina', 'AR', 'ARG', 'ar.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (11, 'American Samoa', 'AS', 'ASM', 'as.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (12, 'Austria', 'AT', 'AUT', 'at.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (13, 'Australia', 'AU', 'AUS', 'au.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (14, 'Aruba', 'AW', 'ABW', 'aw.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (15, 'Åland', 'AX', 'ALA', 'ax.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (16, 'Azerbaijan', 'AZ', 'AZE', 'az.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (17, 'Bosnia and Herzegovina', 'BA', 'BIH', 'ba.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (18, 'Barbados', 'BB', 'BRB', 'bb.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (19, 'Bangladesh', 'BD', 'BGD', 'bd.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (20, 'Belgium', 'BE', 'BEL', 'be.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (21, 'Burkina Faso', 'BF', 'BFA', 'bf.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (22, 'Bulgaria', 'BG', 'BGR', 'bg.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (23, 'Bahrain', 'BH', 'BHR', 'bh.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (24, 'Burundi', 'BI', 'BDI', 'bi.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (25, 'Benin', 'BJ', 'BEN', 'bj.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (26, 'Saint Barthélemy', 'BL', 'BLM', 'bl.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (27, 'Bermuda', 'BM', 'BMU', 'bm.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (28, 'Brunei', 'BN', 'BRN', 'bn.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (29, 'Bolivia', 'BO', 'BOL', 'bo.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (30, 'Bonaire', 'BQ', 'BES', 'bq.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (31, 'Brazil', 'BR', 'BRA', 'br.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (32, 'Bahamas', 'BS', 'BHS', 'bs.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (33, 'Bhutan', 'BT', 'BTN', 'bt.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (34, 'Bouvet Island', 'BV', 'BVT', 'bv.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (35, 'Botswana', 'BW', 'BWA', 'bw.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (36, 'Belarus', 'BY', 'BLR', 'by.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (37, 'Belize', 'BZ', 'BLZ', 'bz.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (38, 'Canada', 'CA', 'CAN', 'ca.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (39, 'Cocos [Keeling] Islands', 'CC', 'CCK', 'cc.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (40, 'Democratic Republic of the Congo', 'CD', 'COD', 'cd.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (41, 'Central African Republic', 'CF', 'CAF', 'cf.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (42, 'Republic of the Congo', 'CG', 'COG', 'cg.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (43, 'Switzerland', 'CH', 'CHE', 'ch.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (44, 'Ivory Coast', 'CI', 'CIV', 'ci.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (45, 'Cook Islands', 'CK', 'COK', 'ck.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (46, 'Chile', 'CL', 'CHL', 'cl.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (47, 'Cameroon', 'CM', 'CMR', 'cm.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (48, 'China', 'CN', 'CHN', 'cn.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (49, 'Colombia', 'CO', 'COL', 'co.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (50, 'Costa Rica', 'CR', 'CRI', 'cr.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (51, 'Cuba', 'CU', 'CUB', 'cu.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (52, 'Cape Verde', 'CV', 'CPV', 'cv.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (53, 'Curacao', 'CW', 'CUW', 'cw.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (54, 'Christmas Island', 'CX', 'CXR', 'cx.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (55, 'Cyprus', 'CY', 'CYP', 'cy.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (56, 'Czechia', 'CZ', 'CZE', 'cz.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (57, 'Germany', 'DE', 'DEU', 'de.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (58, 'Djibouti', 'DJ', 'DJI', 'dj.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (59, 'Denmark', 'DK', 'DNK', 'dk.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (60, 'Dominica', 'DM', 'DMA', 'dm.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (61, 'Dominican Republic', 'DO', 'DOM', 'do.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (62, 'Algeria', 'DZ', 'DZA', 'dz.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (63, 'Ecuador', 'EC', 'ECU', 'ec.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (64, 'Estonia', 'EE', 'EST', 'ee.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (65, 'Egypt', 'EG', 'EGY', 'eg.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (66, 'Western Sahara', 'EH', 'ESH', 'eh.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (67, 'Eritrea', 'ER', 'ERI', 'er.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (68, 'Spain', 'ES', 'ESP', 'es.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (69, 'Ethiopia', 'ET', 'ETH', 'et.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (70, 'Finland', 'FI', 'FIN', 'fi.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (71, 'Fiji', 'FJ', 'FJI', 'fj.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (72, 'Falkland Islands', 'FK', 'FLK', 'fk.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (73, 'Micronesia', 'FM', 'FSM', 'fm.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (74, 'Faroe Islands', 'FO', 'FRO', 'fo.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (75, 'France', 'FR', 'FRA', 'fr.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (76, 'Gabon', 'GA', 'GAB', 'ga.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (77, 'United Kingdom', 'GB', 'GBR', 'gb.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (78, 'Grenada', 'GD', 'GRD', 'gd.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (79, 'Georgia', 'GE', 'GEO', 'ge.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (80, 'French Guiana', 'GF', 'GUF', 'gf.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (81, 'Guernsey', 'GG', 'GGY', 'gg.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (82, 'Ghana', 'GH', 'GHA', 'gh.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (83, 'Gibraltar', 'GI', 'GIB', 'gi.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (84, 'Greenland', 'GL', 'GRL', 'gl.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (85, 'Gambia', 'GM', 'GMB', 'gm.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (86, 'Guinea', 'GN', 'GIN', 'gn.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (87, 'Guadeloupe', 'GP', 'GLP', 'gp.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (88, 'Equatorial Guinea', 'GQ', 'GNQ', 'gq.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (89, 'Greece', 'GR', 'GRC', 'gr.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (90, 'South Georgia and the South Sandwich Islands', 'GS', 'SGS', 'gs.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (91, 'Guatemala', 'GT', 'GTM', 'gt.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (92, 'Guam', 'GU', 'GUM', 'gu.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (93, 'Guinea-Bissau', 'GW', 'GNB', 'gw.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (94, 'Guyana', 'GY', 'GUY', 'gy.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (95, 'Hong Kong', 'HK', 'HKG', 'hk.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (96, 'Heard Island and McDonald Islands', 'HM', 'HMD', 'hm.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (97, 'Honduras', 'HN', 'HND', 'hn.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (98, 'Croatia', 'HR', 'HRV', 'hr.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (99, 'Haiti', 'HT', 'HTI', 'ht.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (100, 'Hungary', 'HU', 'HUN', 'hu.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (101, 'Indonesia', 'ID', 'IDN', 'id.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (102, 'Ireland', 'IE', 'IRL', 'ie.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (103, 'Israel', 'IL', 'ISR', 'il.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (104, 'Isle of Man', 'IM', 'IMN', 'im.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (105, 'India', 'IN', 'IND', 'in.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (106, 'British Indian Ocean Territory', 'IO', 'IOT', 'io.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (107, 'Iraq', 'IQ', 'IRQ', 'iq.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (108, 'Iran', 'IR', 'IRN', 'ir.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (109, 'Iceland', 'IS', 'ISL', 'is.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (110, 'Italy', 'IT', 'ITA', 'it.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (111, 'Jersey', 'JE', 'JEY', 'je.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (112, 'Jamaica', 'JM', 'JAM', 'jm.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (113, 'Jordan', 'JO', 'JOR', 'jo.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (114, 'Japan', 'JP', 'JPN', 'jp.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (115, 'Kenya', 'KE', 'KEN', 'ke.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (116, 'Kyrgyzstan', 'KG', 'KGZ', 'kg.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (117, 'Cambodia', 'KH', 'KHM', 'kh.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (118, 'Kiribati', 'KI', 'KIR', 'ki.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (119, 'Comoros', 'KM', 'COM', 'km.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (120, 'Saint Kitts and Nevis', 'KN', 'KNA', 'kn.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (121, 'North Korea', 'KP', 'PRK', 'kp.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (122, 'South Korea', 'KR', 'KOR', 'kr.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (123, 'Kuwait', 'KW', 'KWT', 'kw.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (124, 'Cayman Islands', 'KY', 'CYM', 'ky.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (125, 'Kazakhstan', 'KZ', 'KAZ', 'kz.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (126, 'Laos', 'LA', 'LAO', 'la.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (127, 'Lebanon', 'LB', 'LBN', 'lb.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (128, 'Saint Lucia', 'LC', 'LCA', 'lc.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (129, 'Liechtenstein', 'LI', 'LIE', 'li.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (130, 'Sri Lanka', 'LK', 'LKA', 'lk.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (131, 'Liberia', 'LR', 'LBR', 'lr.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (132, 'Lesotho', 'LS', 'LSO', 'ls.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (133, 'Lithuania', 'LT', 'LTU', 'lt.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (134, 'Luxembourg', 'LU', 'LUX', 'lu.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (135, 'Latvia', 'LV', 'LVA', 'lv.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (136, 'Libya', 'LY', 'LBY', 'ly.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (137, 'Morocco', 'MA', 'MAR', 'ma.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (138, 'Monaco', 'MC', 'MCO', 'mc.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (139, 'Moldova', 'MD', 'MDA', 'md.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (140, 'Montenegro', 'ME', 'MNE', 'me.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (141, 'Saint Martin', 'MF', 'MAF', 'mf.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (142, 'Madagascar', 'MG', 'MDG', 'mg.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (143, 'Marshall Islands', 'MH', 'MHL', 'mh.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (144, 'Macedonia', 'MK', 'MKD', 'mk.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (145, 'Mali', 'ML', 'MLI', 'ml.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (146, 'Myanmar [Burma]', 'MM', 'MMR', 'mm.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (147, 'Mongolia', 'MN', 'MNG', 'mn.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (148, 'Macao', 'MO', 'MAC', 'mo.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (149, 'Northern Mariana Islands', 'MP', 'MNP', 'mp.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (150, 'Martinique', 'MQ', 'MTQ', 'mq.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (151, 'Mauritania', 'MR', 'MRT', 'mr.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (152, 'Montserrat', 'MS', 'MSR', 'ms.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (153, 'Malta', 'MT', 'MLT', 'mt.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (154, 'Mauritius', 'MU', 'MUS', 'mu.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (155, 'Maldives', 'MV', 'MDV', 'mv.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (156, 'Malawi', 'MW', 'MWI', 'mw.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (157, 'Mexico', 'MX', 'MEX', 'mx.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (158, 'Malaysia', 'MY', 'MYS', 'my.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (159, 'Mozambique', 'MZ', 'MOZ', 'mz.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (160, 'Namibia', 'NA', 'NAM', 'na.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (161, 'New Caledonia', 'NC', 'NCL', 'nc.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (162, 'Niger', 'NE', 'NER', 'ne.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (163, 'Norfolk Island', 'NF', 'NFK', 'nf.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (164, 'Nigeria', 'NG', 'NGA', 'ng.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (165, 'Nicaragua', 'NI', 'NIC', 'ni.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (166, 'Netherlands', 'NL', 'NLD', 'nl.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (167, 'Norway', 'NO', 'NOR', 'no.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (168, 'Nepal', 'NP', 'NPL', 'np.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (169, 'Nauru', 'NR', 'NRU', 'nr.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (170, 'Niue', 'NU', 'NIU', 'nu.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (171, 'New Zealand', 'NZ', 'NZL', 'nz.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (172, 'Oman', 'OM', 'OMN', 'om.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (173, 'Panama', 'PA', 'PAN', 'pa.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (174, 'Peru', 'PE', 'PER', 'pe.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (175, 'French Polynesia', 'PF', 'PYF', 'pf.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (176, 'Papua New Guinea', 'PG', 'PNG', 'pg.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (177, 'Philippines', 'PH', 'PHL', 'ph.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (178, 'Pakistan', 'PK', 'PAK', 'pk.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (179, 'Poland', 'PL', 'POL', 'pl.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (180, 'Saint Pierre and Miquelon', 'PM', 'SPM', 'pm.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (181, 'Pitcairn Islands', 'PN', 'PCN', 'pn.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (182, 'Puerto Rico', 'PR', 'PRI', 'pr.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (183, 'Palestine', 'PS', 'PSE', 'ps.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (184, 'Portugal', 'PT', 'PRT', 'pt.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (185, 'Palau', 'PW', 'PLW', 'pw.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (186, 'Paraguay', 'PY', 'PRY', 'py.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (187, 'Qatar', 'QA', 'QAT', 'qa.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (188, 'Réunion', 'RE', 'REU', 're.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (189, 'Romania', 'RO', 'ROU', 'ro.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (190, 'Serbia', 'RS', 'SRB', 'rs.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (191, 'Russia', 'RU', 'RUS', 'ru.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (192, 'Rwanda', 'RW', 'RWA', 'rw.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (193, 'Saudi Arabia', 'SA', 'SAU', 'sa.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (194, 'Solomon Islands', 'SB', 'SLB', 'sb.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (195, 'Seychelles', 'SC', 'SYC', 'sc.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (196, 'Sudan', 'SD', 'SDN', 'sd.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (197, 'Sweden', 'SE', 'SWE', 'se.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (198, 'Singapore', 'SG', 'SGP', 'sg.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (199, 'Saint Helena', 'SH', 'SHN', 'sh.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (200, 'Slovenia', 'SI', 'SVN', 'si.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (201, 'Svalbard and Jan Mayen', 'SJ', 'SJM', 'sj.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (202, 'Slovakia', 'SK', 'SVK', 'sk.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (203, 'Sierra Leone', 'SL', 'SLE', 'sl.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (204, 'San Marino', 'SM', 'SMR', 'sm.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (205, 'Senegal', 'SN', 'SEN', 'sn.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (206, 'Somalia', 'SO', 'SOM', 'so.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (207, 'Suriname', 'SR', 'SUR', 'sr.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (208, 'South Sudan', 'SS', 'SSD', 'ss.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (209, 'São Tomé and Príncipe', 'ST', 'STP', 'st.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (210, 'El Salvador', 'SV', 'SLV', 'sv.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (211, 'Sint Maarten', 'SX', 'SXM', 'sx.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (212, 'Syria', 'SY', 'SYR', 'sy.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (213, 'Swaziland', 'SZ', 'SWZ', 'sz.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (214, 'Turks and Caicos Islands', 'TC', 'TCA', 'tc.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (215, 'Chad', 'TD', 'TCD', 'td.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (216, 'French Southern Territories', 'TF', 'ATF', 'tf.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (217, 'Togo', 'TG', 'TGO', 'tg.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (218, 'Thailand', 'TH', 'THA', 'th.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (219, 'Tajikistan', 'TJ', 'TJK', 'tj.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (220, 'Tokelau', 'TK', 'TKL', 'tk.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (221, 'East Timor', 'TL', 'TLS', 'tl.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (222, 'Turkmenistan', 'TM', 'TKM', 'tm.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (223, 'Tunisia', 'TN', 'TUN', 'tn.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (224, 'Tonga', 'TO', 'TON', 'to.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (225, 'Turkey', 'TR', 'TUR', 'tr.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (226, 'Trinidad and Tobago', 'TT', 'TTO', 'tt.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (227, 'Tuvalu', 'TV', 'TUV', 'tv.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (228, 'Taiwan', 'TW', 'TWN', 'tw.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (229, 'Tanzania', 'TZ', 'TZA', 'tz.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (230, 'Ukraine', 'UA', 'UKR', 'ua.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (231, 'Uganda', 'UG', 'UGA', 'ug.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (232, 'U.S. Minor Outlying Islands', 'UM', 'UMI', 'um.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (233, 'United States', 'US', 'USA', 'us.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (234, 'Uruguay', 'UY', 'URY', 'uy.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (235, 'Uzbekistan', 'UZ', 'UZB', 'uz.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (236, 'Vatican City', 'VA', 'VAT', 'va.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (237, 'Saint Vincent and the Grenadines', 'VC', 'VCT', 'vc.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (238, 'Venezuela', 'VE', 'VEN', 've.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (239, 'British Virgin Islands', 'VG', 'VGB', 'vg.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (240, 'U.S. Virgin Islands', 'VI', 'VIR', 'vi.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (241, 'Vietnam', 'VN', 'VNM', 'vn.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (242, 'Vanuatu', 'VU', 'VUT', 'vu.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (243, 'Wallis and Futuna', 'WF', 'WLF', 'wf.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (244, 'Samoa', 'WS', 'WSM', 'ws.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (245, 'Kosovo', 'XK', 'XKX', 'xk.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (246, 'Yemen', 'YE', 'YEM', 'ye.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (247, 'Mayotte', 'YT', 'MYT', 'yt.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (248, 'South Africa', 'ZA', 'ZAF', 'za.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (249, 'Zambia', 'ZM', 'ZMB', 'zm.svg');
INSERT INTO country (id_country, name_country, iso_country, iso3_country, flag_country) VALUES (250, 'Zimbabwe', 'ZW', 'ZWE', 'zw.svg');