<?php
/**
 * Created by PhpStorm.
 * User: caiop
 * Date: 20/11/2018
 * Time: 16:34
 */

namespace app\controller;

use app\model\AlbumModel;
use core\mvc\Controller;
use app\model\SongModel;
use app\dao\SongDao;

final class SongCtr extends Controller
{

    public function __construct(SongModel $model = null)
    {
        parent::__construct();
        $this->model = is_null($model) ? new SongModel() : $model ;
        $this->dao = new SongDao();
    }

    /**
     * Pega os dados da model e alimenta a View - abstrato, pois será implementados nos herdeiros.
     */
    public function viewToModel()
    {
        $this->model = new SongModel(
            $this->model->getId(),
            $this->model->getNameSong(),
            $this->model->getNumberSong(),
            $this->model->getLengthSong(),
            $this->model->getLyricsSong(),
            new AlbumModel($this->model->getAlbum()->getId())
        );
        // TODO: Implement viewToModel() method.
    }

    public function showList()
    {
        $this->orderBy = SongDao::COL_NUMBER . ' ASC';
        parent::showList(); // TODO: Change the autogenerated stub
    }

    public function run($delete = null)
    {
        if (!$delete) {
            $this->insertUpdate();
        } else {
            $this->delete();
        }
        //parent::run(); // TODO: Change the autogenerated stub
    }

    public function insertUpdate()
    {
        try {
            //..alimenta o model com os dados da View
            $this->viewToModel();
            //..seta o modelo atualizado no objeto DAO
            $this->dao->setModel($this->model);
            //..invoca o método insertUpdate para persistir o Model
            $this->dao->insertUpdate();
        } catch (Exception $ex) {
            throw $ex;
        }
        //parent::insertUpdate(); // TODO: Change the autogenerated stub
    }
}