<div class="col-sm-10 offset-sm-1">

    <div class="row">
        <div class="col-sm-6">
            <h4>Gêneros:</h4>
        </div>
        <?php if ($this->activeUser != new \app\model\UserModel() && $this->activeUser->getTypeUser() != "U") { ?>
            <div class="col-sm-6 text-right">
                <a href="/Metalpedia/generos/cadastrar">
                    <button type="button" class="btn btn-danger btn-sm">
                        <i class="fas fa-plus"></i> Cadastrar
                    </button>
                </a>
            </div>
        <?php } ?>
    </div>

    <!--<form name="searchform" method="post" action="Request.php?class=GenreCtr&method=showList&page=1">-->
    <form name="searchform" method="post" action="/Metalpedia/generos?page=1">

        <table class="table table-dark table-borderless mb-4">
            <thead>
            <tr>
                <th>Reg. Por Página:</th>
                <th>Gênero:</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    <select class="custom-select" name="limit" id="limit">
                        <option <?= $this->regPerPage == 10 ? "selected" : '' ?> value="10">10</option>
                        <option <?= $this->regPerPage == 25 ? "selected" : '' ?> value="25">25</option>
                        <option <?= $this->regPerPage == 50 ? "selected" : '' ?> value="50">50</option>
                        <option <?= $this->regPerPage == 100 ? "selected" : '' ?> value="100">100</option>
                    </select>
                </td>
                <td>
                    <div class="input-group">
                        <input type="text" class="form-control custom-input" name="data[0]" id="name" value="<?= $this->sqlData[0] ?>" placeholder="Pesquisar...">
                        <div class="input-group-append">
                            <button class="btn btn-danger" type="submit" name="command" title="Pesquisar"><i class="fas fa-filter fa-sm"></i> Filtrar</button>
                        </div>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>

    </form>

    <?php
    $this->createList(
        $this->model,
        array('Gênero', 'Nº Bandas', 'Nº Álbums'),
        array('getNameGenre'),
        'GenreCtr'
    );

    $this->createPagination('GenreCtr');

    ?>

</div>