</div>
</section>
    <footer class="text-center">
        <p><small><?=core\Application::APP_NAME ?> &reg 2018</small></p>
    </footer>

    <!-- JS -->
    <script src="/Metalpedia/core/vendor/js/jquery-3.3.1.min.js"></script>
    <script src="/Metalpedia/core/vendor/js/popper.min.js"></script>
    <script src="/Metalpedia/core/vendor/bootstrap/js/bootstrap.js"></script>
    <script src="/Metalpedia/core/vendor/js/bootstrap-select.js"></script>
    <script src="/Metalpedia/core/vendor/js/jquery.form-validator.min.js"></script>
    <script src="/Metalpedia/core/vendor/js/main.js"></script>

</body>
</html>