<?php
//..configurar os uses
use core\Application;
use core\util\Session;

//..se houver a sessão active user criada, então pega ela...
//$this->activeUser = Session::getSession('activeUser') ? Session::getSession('activeUser') : 'Visitante';
$this->activeUser = Session::getSession('activeUser') ? Session::getSession('activeUser') : new \app\model\UserModel();

?>
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        <?=core\Application::APP_NAME ?>
    </title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/Metalpedia/core/vendor/bootstrap/css/bootstrap.css">
    <!-- Main CSS -->
    <link rel="stylesheet" href="/Metalpedia/core/vendor/css/main.css">
    <!-- Bootstrap-Select CSS -->
    <link rel="stylesheet" href="/Metalpedia/core/vendor/css/bootstrap-select.css">
    <!-- Font Awesome Icons CSS -->
    <link rel="stylesheet" href="/Metalpedia/core/vendor/font-awesome/css/all.css">
    <!-- Favicon -->
    <link rel="shortcut icon" href="/Metalpedia/core/img/favicon.ico">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="navbar-collapse collapse w-100 dual-collapse2 order-1 order-md-0">
                <ul class="navbar-nav ml-auto mr-auto text-center">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Bandas
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="/Metalpedia/bandas">Bandas</a>
                            <a class="dropdown-item" href="/Metalpedia/paises">Países</a>
                            <a class="dropdown-item" href="/Metalpedia/generos">Gêneros</a>
                            <?php if($this->activeUser != new \app\model\UserModel()) { ?>
                                <a class="dropdown-item" href="/Metalpedia/bandas/cadastrar">Cadastrar</a>
                            <?php } ?>
                        </div>
                    </li>
                    <?php if($this->activeUser->getTypeUser() == null || $this->activeUser->getTypeUser() == 'U') { ?>
                        <li class="nav-item">
                            <a class="nav-link" href="/Metalpedia/albums">Álbums</a>
                        </li>
                    <?php } ?>
                    <?php if ($this->activeUser->getTypeUser() != null && $this->activeUser->getTypeUser() != 'U') { ?>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Álbuns
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="/Metalpedia/albums">Álbums</a>
                                <a class="dropdown-item" href="/Metalpedia/albums/cadastrar">Cadastrar</a>
                            </div>
                        </li>
                    <?php } ?>
                    <?php if ($this->activeUser->getTypeUser() != null && $this->activeUser->getTypeUser() != 'U') { ?>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Países
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="/Metalpedia/paises">Países</a>
                                <a class="dropdown-item" href="/Metalpedia/paises/cadastrar">Cadastrar</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Gêneros
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="/Metalpedia/generos">Gêneros</a>
                                <a class="dropdown-item" href="/Metalpedia/generos/cadastrar">Cadastrar</a>
                            </div>
                        </li>
                    <?php } ?>
                </ul>
            </div>
            <div class="mx-auto my-2 order-0 order-md-1 text-center">
                <a class="mx-auto logo" href="/Metalpedia/">
                    <?=core\Application::APP_NAME ?>
                </a>
            </div>
            <div class="container navbar-toggler" style="border: 0">
                <span class="icon nav-link" data-toggle="collapse" data-target=".dual-collapse2">&#9776;</span>
            </div>
            <div class="navbar-collapse collapse w-100 dual-collapse2 order-2 order-md-2">
                <ul class="navbar-nav mr-auto ml-auto text-center">
                    <?php if ($this->activeUser == new \app\model\UserModel()) { ?>
                        <li class="nav-item">
                            <a class="nav-link" href="/Metalpedia/cadastrar">Cadastrar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Metalpedia/entrar">Entrar</a>
                        </li>
                    <?php } else { ?>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <?=$this->activeUser->getNameUser()?>
                            </a>
                            <div class="dropdown-menu">
                                <div class="row">
                                    <div class="col-sm-8 text-right">
                                        <p class="text-white"><?=$this->activeUser->getFullTypeUser()?></p>
                                    </div>
                                    <div class="col-sm-4">
                                        <img style="max-width: 50px; max-height: 50px;" src="<?=$this->activeUser->getAvatarUser()?>">
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Metalpedia/sair">Sair</a>
                        </li>
                    <?php } ?>
                </ul>
            </div>
        </nav>
    </header>
    
    <section class="content">
        <div class="container">