<?php
/**
 * Created by PhpStorm.
 * User: caiop
 * Date: 15/11/2018
 * Time: 14:24
 */

namespace app\view\album;

use core\mvc\view\HtmlPage;
use core\util\Session;

final class AlbumList extends HtmlPage
{

    protected $orderBy;
    protected $album_types;

    public function __construct($model = null, $sqlData = null, $regPerPage = null, $currentPage = null, $previousPage = null, $nextPage = null, $lastPage = null, $album_types = null)
    {
        parent::__construct($model, $sqlData, $regPerPage, $currentPage, $previousPage, $nextPage, $lastPage);
        $this->album_types = $album_types;
        $this->htmlFile = 'app/view/album/album_list.phtml';
    }

    public function show()
    {
        $this->orderBy = Session::getSession("orderBy") != null ? Session::getSession("orderBy") : "name_band, id_band";
        parent::show(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getOrderBy()
    {
        return $this->orderBy;
    }

    /**
     * @param mixed $orderBy
     */
    public function setOrderBy($orderBy)
    {
        $this->orderBy = $orderBy;
    }

    /**
     * @return null
     */
    public function getAlbumTypes()
    {
        return $this->album_types;
    }

    /**
     * @param null $album_types
     */
    public function setAlbumTypes($album_types)
    {
        $this->album_types = $album_types;
    }

}