<?php
/**
 * Created by PhpStorm.
 * User: caiop
 * Date: 26/10/2018
 * Time: 22:50
 */

namespace app\view\band;

use core\mvc\view\HtmlPage;
use core\util\Session;

final class BandList extends HtmlPage
{

    protected $orderBy;
    protected $countries;

    public function __construct($model = null, $sqlData = null, $regPerPage = null, $currentPage = null, $previousPage = null, $nextPage = null, $lastPage = null)
    {
        parent::__construct($model, $sqlData, $regPerPage, $currentPage, $previousPage, $nextPage, $lastPage);
        $this->htmlFile = 'app/view/band/band_list.phtml';
    }

    public function show()
    {
        $this->orderBy = Session::getSession("orderBy") != null ? Session::getSession("orderBy") : "name_band, id_band";
        parent::show(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getOrderBy()
    {
        return $this->orderBy;
    }

    /**
     * @param mixed $orderBy
     */
    public function setOrderBy($orderBy)
    {
        $this->orderBy = $orderBy;
    }

    /**
     * @return mixed
     */
    public function getCountries()
    {
        return $this->countries;
    }

    /**
     * @param mixed $countries
     */
    public function setCountries($countries)
    {
        $this->countries = $countries;
    }

}