<div class="col-sm-10 offset-sm-1">

    <div class="row">
        <div class="col-sm-6">
            <h4>Bandas:</h4>
        </div>
        <?php if ($this->activeUser != 'Visitante') { ?>
            <div class="col-sm-6 text-right">
                <a href="/Metalpedia/bandas/cadastrar">
                    <button type="button" class="btn btn-danger btn-sm">
                        <i class="fas fa-plus"></i> Cadastrar
                    </button>
                </a>
            </div>
        <?php } ?>
    </div>

    <form name="searchform" method="post" action="/Metalpedia/bandas?page=1">
        <table class="table table-dark table-borderless">
            <thead>
            <tr>
                <th>Reg. Por Página:</th>
                <th>País:</th>
                <th>Gênero:</th>
            </tr>
            </thead>
            <tbody>
            <tr class="align-middle">
                <td>
                    <select class="custom-select" name="limit" id="limit">
                        <option <?= $this->regPerPage == 10 ? "selected" : '' ?> value="10">10</option>
                        <option <?= $this->regPerPage == 25 ? "selected" : '' ?> value="25">25</option>
                        <option <?= $this->regPerPage == 50 ? "selected" : '' ?> value="50">50</option>
                        <option <?= $this->regPerPage == 100 ? "selected" : '' ?> value="100">100</option>
                    </select>
                </td>
                <td>
                    <div class="input-group">
                        <input type="text" class="form-control custom-input" id="rdoname_country"
                               value="<?= isset($this->sqlData[0]) ? $this->sqlData[0] : '' ?>" placeholder="..."
                               readonly>
                        <input type="hidden" name="data[0]" id="id_country" value="<?= isset($this->sqlData[0]) ? $this->sqlData[0] : '' ?>">
                        <div class="input-group-append">
                            <!--<span class="input-group-text"><i class="fas fa-search"></i></span>-->
                            <button type="button" class="btn btn-danger" name="search_country" id="search_country" title="Pesquisar"><i class="fas fa-search"></i></button>
                        </div>
                    </div>
                </td>
                <td>
                    <div class="input-group">
                        <input type="text" class="form-control custom-input" id="rdoname_genre"
                               value="<?= isset($this->sqlData[1]) ? $this->sqlData[1] : '' ?>" placeholder="..."
                               readonly>
                        <input type="hidden" name="data[1]" id="id_genre" value="<?= isset($this->sqlData[1]) ? $this->sqlData[1] : '' ?>">
                        <div class="input-group-append">
                            <!--<span class="input-group-text"><i class="fas fa-search"></i></span>-->
                            <button type="button" class="btn btn-danger" name="search_genre" id="search_genre" title="Pesquisar"><i class="fas fa-search"></i></button>
                        </div>
                </td>
            </tr>
            </tbody>
            <thead>
            <tr>
                <th>Ordenar Por:</th>
                <th>Nome:</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    <select class="custom-select" name="orderBy" id="orderBy">
                        <option value="<?=(new \app\dao\BandDao())::COL_BAND?> asc"
                            <?= $this->orderBy == ((new \app\dao\BandDao())::COL_BAND . " asc") ? "selected" : '' ?>>
                            Nome &#8638;
                        </option>
                        <option value="<?=(new \app\dao\BandDao())::COL_BAND?> desc"
                            <?= $this->orderBy == ((new \app\dao\BandDao())::COL_BAND . " desc") ? "selected" : '' ?>>
                            Nome &#8643;
                        </option>
                        <option value="<?=(new \app\dao\BandDao())::COL_GENRE?> asc"
                            <?= $this->orderBy == ((new \app\dao\BandDao())::COL_GENRE . " asc") ? "selected" : '' ?>>
                            Gênero &#8638;
                        </option>
                        <option value="<?=(new \app\dao\BandDao())::COL_GENRE?> desc"
                            <?= $this->orderBy == ((new \app\dao\BandDao())::COL_GENRE . " desc") ? "selected" : '' ?>>
                            Gênero &#8643;
                        </option>
                        <option value="<?=(new \app\dao\BandDao())::COL_COUNTRY?> asc"
                            <?= $this->orderBy == ((new \app\dao\BandDao())::COL_COUNTRY . " asc") ? "selected" : '' ?>>
                            País &#8638;
                        </option>
                        <option value="<?=(new \app\dao\BandDao())::COL_COUNTRY?> desc"
                            <?= $this->orderBy == ((new \app\dao\BandDao())::COL_COUNTRY . " desc") ? "selected" : '' ?>>
                            País &#8643;
                        </option>
                    </select>
                </td>
                <td colspan="2">
                    <div class="input-group">
                        <input type="text" class="form-control custom-input" name="data[2]" id="name" value="<?= isset($this->sqlData[2]) ? $this->sqlData[2] : '' ?>" placeholder="Pesquisar...">
                        <div class="input-group-append">
                            <button class="btn btn-block btn-danger" type="submit" name="command" title="Filtrar">
                                <i class="fas fa-filter fa-sm"></i> Filtrar
                            </button>
                        </div>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </form>

    <div id="view-list" class="card-group mt-5">

        <?php if (sizeof($this->model) == 0) { ?>
            <div class="container-fluid mt-3 text-center">
                <span>Nenhum Registro Encontrado!</span>
            </div>
        <?php } ?>

        <?php foreach ($this->model as $band) { ?>

        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-6 mb-5">

            <div class="grid__item mb-4">
                <a class="grid__link" href="/Metalpedia/bandas/<?=$band->getId()?>" title="<?=$band->getNameBand()?>">
                    <div class="img-wrap img-wrap--grid">
                        <img class="img img--grid" src="/Metalpedia/core/img/photos/<?=$band->getPhotoBand()?>" alt="album1">
                    </div>
                </a>
                <span class="year"><?=$band->getGenre()->getNameGenre()?></span>
                <span class="artist"><?=$band->getCountry()->getNameCountry()?></span>
                <span class="title"><?=$band->getNameBand()?></span>
            </div>

        </div>

        <?php } ?>
    </div>

    <?php
    if ($this->model)
        $this->createPagination('BandCtr');
    ?>

    <?php
    /*$this->createList(
        $this->model,
        array('Nome', 'ISO', 'ISO3', 'Bandeira'),
        array('getNameCountry', 'getIsoCountry', 'getIso3Country', 'getFlagCountry'),
        'CountryCtr'
    );*/

    ?>

</div>

<!-- Country Modal -->
<div class="modal fade" id="countryModal" tabindex="-1" role="dialog" aria-labelledby="countryModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-dark">Países</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true" class="text-white">&times;</span>
                </button>
            </div>
            <div class="modal-body p-0 m-0">
                <div class="form-group mb-0">
                    <div class="input-group">
                        <input type="text" class="form-control" name="name_country" id="name_country" value="" placeholder="Pesquisar...">
                        <div class="input-group-append">
                            <button type="button" class="btn btn-danger btn-xs" name="btn-search-country" id="btn-search-country" title="Pesquisar">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </div>
                <table id="countries-table" class="table table-striped table-borderless">
                    <thead class="thead-dark">
                    <tr>
                        <th>Nome</th>
                        <th>ISO</th>
                        <th>ISO3</th>
                        <th class="text-right">#</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Genre Modal -->
<div class="modal fade" id="genreModal" tabindex="-1" role="dialog" aria-labelledby="genreModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-dark">Gêneros</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true" class="text-white">&times;</span>
                </button>
            </div>
            <div class="modal-body p-0 m-0">
                <div class="form-group mb-0">
                    <div class="input-group">
                        <input type="text" class="form-control" name="name_genre" id="name_genre" value="" placeholder="Pesquisar...">
                        <div class="input-group-append">
                            <button type="button" class="btn btn-danger btn-xs" name="btn-search-genre" id="btn-search-genre" title="Pesquisar">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </div>
                <table id="genres-table" class="table table-striped table-borderless">
                    <thead class="thead-dark">
                    <tr>
                        <th>Gênero</th>
                        <th class="text-right">#</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- JQuery JS -->
<script src="/Metalpedia/core/vendor/js/jquery-3.3.1.min.js"></script>
<script !src="">
    $("#search_country").on('click', function () {
        $("#countryModal").modal('toggle');
        $("#btn-search-country").trigger("click");
    });

    $("#search_genre").on('click', function () {
        $("#genreModal").modal('toggle');
        $("#btn-search-genre").trigger("click");
    });

    $("#btn-search-country").on('click', function () {
        $("#countries-table tbody").html("");
        //if($("#name_country").val() != ''){
        url = "http://localhost/Metalpedia/Request.php?class=CountryCtr&method=getCountries&name_country=" + $("#name_country").val();
        $.getJSON(url, function (data) {
            $("#countries-table tbody").append("<tr>\n" +
                "                        <td class=\"align-middle\">Todos</td>\n" +
                "                        <td class=\"align-middle\"></td>\n" +
                "                        <td class=\"align-middle\"></td>\n" +
                "                        <td class=\"text-right\">\n" +
                "                            <button type=\"button\" class=\"btn btn-danger btn-sm btn-select-country\" name=\"\" id=\"\"><i class=\"fas fa-check fa-xs\"></i></button>\n" +
                "                        </td>\n" +
                "                    </tr>");
                if(!data.status){
                    $.each(data, function (key, value) {
                        $("#countries-table tbody").append("<tr>\n" +
                            "                        <td class=\"align-middle\"><span class=\""+value.iso_country.toLowerCase()+" flag\"'></span>"+value.name_country+"</td>\n" +
                            "                        <td class=\"align-middle\">"+value.iso_country+"</td>\n" +
                            "                        <td class=\"align-middle\">"+value.iso3_country+"</td>\n" +
                            "                        <td class=\"text-right\">\n" +
                            "                            <button type=\"button\" class=\"btn btn-danger btn-sm btn-select-country\" name=\""+value.name_country+"\" id=\""+value.id_country+"\"><i class=\"fas fa-check fa-xs\"></i></button>\n" +
                            "                        </td>\n" +
                            "                    </tr>");
                    });
                } else {
                    $("#countries-table tbody").append("<tr><td colspan=\"4\" class=\"align-middle text-center\">Nenhum Registro Encontrado</tr>");
                }
            }
        );
        //}
    });

    $("#btn-search-genre").on('click', function () {
        $("#genres-table tbody").html("");
        //if($("#name_country").val() != ''){
        url = "http://localhost/Metalpedia/Request.php?class=GenreCtr&method=getGenres&name_genre=" + $("#name_genre").val();
        $.getJSON(url, function (data) {
            $("#genres-table tbody").append("<tr>\n" +
                "                        <td class=\"align-middle\">Todos</td>\n" +
                "                        <td class=\"text-right\">\n" +
                "                            <button type=\"button\" class=\"btn btn-danger btn-sm btn-select-genre\" name=\"\" id=\"\"><i class=\"fas fa-check fa-xs\"></i></button>\n" +
                "                        </td>\n" +
                "                    </tr>");
                if(!data.status){
                    $.each(data, function (key, value) {
                        $("#genres-table tbody").append("<tr>\n" +
                            "                        <td class=\"align-middle\">"+value.name_genre+"</td>\n" +
                            "                        <td class=\"text-right\">\n" +
                            "                            <button type=\"button\" class=\"btn btn-danger btn-sm btn-select-genre\" name=\""+value.name_genre+"\" id=\""+value.id_genre+"\"><i class=\"fas fa-check fa-xs\"></i></button>\n" +
                            "                        </td>\n" +
                            "                    </tr>");
                    });
                } else {
                    $("#genres-table tbody").append("<tr><td colspan=\"4\" class=\"align-middle text-center\">Nenhum Registro Encontrado</tr>");
                }
            }
        );
        //}
    });

    $(document).on('click', 'button.btn.btn-danger.btn-sm.btn-select-country', function(){
        countryId = $(this).attr('id');
        countryName = $(this).attr('name');
        $('#id_country').val(countryId);
        $('#rdoname_country').val(countryName);
        $("#countryModal").modal('toggle');
        //$("form[name=searchform]").submit();
    });

    $(document).on('click', 'button.btn.btn-danger.btn-sm.btn-select-genre', function(){
        genreId = $(this).attr('id');
        genreName = $(this).attr('name');
        $('#id_genre').val(genreId);
        $('#rdoname_genre').val(genreName);
        $("#genreModal").modal('toggle');
    });
</script>